name: Get Environment Variables
description: Get some variables for deploy depending on the environment

inputs:
  environment:
    description: Type of environment (development, release, production)
    required: true

outputs:
  aws_role_arn:
    description: Use to define the role on aws
    value: ${{ steps.get_env_vars.outputs.aws_role_arn }}

  short_env:
    description: A short term for the env to use in pull-env script and lerna deploy script
    value: ${{ steps.get_env_vars.outputs.short_env }}

  aws_profile:
    description: Usually the same as environment. Used to define AWS profile
    value: ${{ steps.get_env_vars.outputs.aws_profile }}

runs:
  using: "composite"
  steps:
    - name: Set Enviroment Variables
      id: get_env_vars
      shell: bash
      run: |
        case ${{ inputs.environment }} in
          development)
            role=arn:aws:iam::822236045867:role/cicd
            echo "::set-output name=aws_role_arn::$role"
            echo "::set-output name=aws_profile::development"
            echo "::set-output name=short_env::dev"
          ;;
          release)
            echo "::set-output name=aws_role_arn::arn:aws:iam::453497214348:role/cicd"
            echo "::set-output name=aws_profile::release"
            echo "::set-output name=short_env::release"
          ;;
          production)
            echo "::set-output name=aws_role_arn::arn:aws:iam::140981404942:role/cicd"
            echo "::set-output name=aws_profile::production"
            echo "::set-output name=short_env::prod"
          ;;
        esac
