name: Deploy Production
on:
  workflow_call:
    secrets:
      TEST:
        required: true

jobs:
  deploy:
    if: "!contains(github.event.head_commit.message, '[skip-ci]')"
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Testing set env
        run: |
          case $GITHUB_REF_NAME in
            develop)
              echo "aws_profile=development" >> $GITHUB_ENV
              echo "aws_role_arn=arn:aws:iam::822236045867:role/cicd" >> $GITHUB_ENV
              echo "short_env=dev" >> $GITHUB_ENV
            ;;
            release)
              echo "aws_profile=release" >> $GITHUB_ENV
              echo "aws_role_arn=arn:aws:iam::453497214348:role/cicd" >> $GITHUB_ENV
              echo "short_env=release" >> $GITHUB_ENV
            ;;
            main)
              echo "aws_profile=production" >> $GITHUB_ENV
              echo "aws_role_arn=arn:aws:iam::140981404942:role/cicd" >> $GITHUB_ENV
              echo "short_env=prod" >> $GITHUB_ENV
          esac

      - name: Testing env setted
        run: |
          echo $aws_profile
          echo $aws_role_arn
          echo $short_env

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: ''

      - name: Generate and publish release
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: ${{ steps.tag_version.outputs.new_tag }}
          tag: ${{ steps.tag_version.outputs.new_tag }}
          publish: true
