name: Deploy Lambda Functions
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref_name }}

      - name: Testing set env
        id: env_vars
        uses: Yokota-Dev/workflows/.github/actions/get-environment-variables@main
        with:
          environment: development

      - name: Testing env setted
        run: |
          echo ${{ env.vars.aws_role_arn }}
          echo ${{ env.vars.aws_profile }}
          echo ${{ env.vars.short_env }}
